name: social_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_storage: ^4.0.0
  image_picker:
  google_fonts:
  path_provider:
  video_player:
  intl:
  file_picker:
  flutter_video_compress:
  timeago:
  image:
  esys_flutter_share:




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

